apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-gateway-to-frontend
  namespace: reddit-front
spec:
  podSelector:
    matchLabels:
      app: reddit-front

  policyTypes:
    - Ingress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: reddit-gateway
      ports:
        - protocol: TCP
          port: 80
