#from helm-chart/backend/templates/secret.yaml
# Secret for sensitive backend application settings.
# This includes database credentials and AWS access keys.
apiVersion: v1
kind: Secret
metadata:
  name: reddit-app-secret
  namespace: reddit-back
type: Opaque
data:
  # Base64 encoded values
  POSTGRES_DB: "" # reddit_db
  POSTGRES_USER: "" # reddit_user
  POSTGRES_PASSWORD: "" # secure_password
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: "" # AKIAAIABQOAK6XACCESSKEY
