apiVersion: v1
kind: Service
metadata:
  name: reddit-backend-service
spec:
  selector:
    app: reddit-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
