# Internal backend service.
# Receives traffic ONLY from the Gateway via HTTPRoutes.

apiVersion: v1
kind: Service
metadata:
  name: reddit-backend-service
  namespace: reddit-back
spec:
  type: ClusterIP
  selector:
    app: reddit-back
  ports:
    - port: 8000
      targetPort: 8000
