# Runs the frontend application pods.
# Image: zain-front

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zain-front
  namespace: reddit-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reddit-front
  template:
    metadata:
      labels:
        app: reddit-front
    spec:
      containers:
        - name: frontend
          image: "201937184629.dkr.ecr.us-east-1.amazonaws.com/reddit-frontend:e7335ad"
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi
