# Internal ClusterIP service for the frontend.
# This service is referenced by an HTTPRoute in the gateway namespace.

apiVersion: v1
kind: Service
metadata:
  name: reddit-frontend-service
  namespace: reddit-front
spec:
  type: ClusterIP
  selector:
    app: reddit-front
  ports:
    - port: 80
      targetPort: 80
